name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: djodiaxa
          svg_out_path: github-contribution-grid-snake-dark.svg
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push changes
        uses: actions/add-and-commit@v9
        with:
          message: "Generate snake animation"
          branch: output
          create_branch: true
